### ISSUE TITLE
【求问】Numeric类型的DocValues的问题？

### ISSUE THREAD

**Issue by wrkaiser** [LuXugang/Lucene-7.5.0#15]
想问下在.dvm和.dvd文件的哪部分存储了docId到value文件偏移的映射关系呢？或者还是通过其他部分进行逻辑映射呢？

**Comment by wrkaiser** [comment]
看了文档，还是不太明白如何通过docid去查找对应的value值

**Comment by LuXugang** [comment]
> 看了文档，还是不太明白如何通过docid去查找对应的value值

嗯 微信上交流吧
