### ISSUE TITLE
关于flush commit merge的一些疑问

### ISSUE THREAD

**Issue by FFFro** [LuXugang/Lucene-7.5.0#26]
大佬，请问就是在merge的时候，IndexWriter 提供给 MergePolicy 的段集是 SegmentInfos 对象，这个里应该是包括了所有的段，但是像flush之后的并没有commit 的段，没有Segment_N 文件，还在文件系统缓存中，这部分段是怎么参加合并的呢。

**Comment by LuXugang** [comment]
参与合并的段实际是 SegmentCommitInfo，它封装的SegmentInfo是[.si索引文件](https://www.amazingkoala.com.cn/Lucene/suoyinwenjian/2019/0605/63.html)对应在内存中的信息，[Segment_N](https://www.amazingkoala.com.cn/Lucene/suoyinwenjian/2019/0610/65.html)中包含的是一个或多个SegmentCommitInfo。flush后，会生成.si信息在内存中，被封装为SegmentCommitInfo后就可以参与合并了。
