### ISSUE TITLE
关于 WAND 算法的一些问题

### ISSUE THREAD

**Issue by FFFro** [LuXugang/Lucene-7.5.0#30]
目前我们es是5.4版本，希望将Lucene高版本中的 wand 算法集成到当前的Lucene中，用来优化term查询，问下大佬这样可行吗

**Comment by LuXugang** [comment]
你是想要把高版本的Lucene代码移植到低版本中的吗
如果是的话，不仅仅要移植跟WAND算法相关逻辑，还要同时要移植索引文件的代码，非常不建议呀

可以把新的业务数据写到高版本的es中，或者将旧版本的es中的数据重新索引到新版本中

**Comment by FFFro** [comment]
> 你是想要把高版本的Lucene代码移植到低版本中的吗 如果是的话，不仅仅要移植跟WAND算法相关逻辑，还要同时要移植索引文件的代码，非常不建议呀
> 
> 可以把新的业务数据写到高版本的es中，或者将旧版本的es中的数据重新索引到新版本中

如果只移植wand算法可以实现吗，不涉及索引文件的改动

**Comment by LuXugang** [comment]
> 

不可以，WAND算法依赖索引文件.doc中[impact](https://www.amazingkoala.com.cn/Lucene/Search/2020/0904/165.html)的信息，并且打分公式接口的都是对应发生变化
